services:
  service-core:
    build: ./service-core
    ports:
      - "8000:8000"
    depends_on:
      - service-database
  service-database:
    build: ./service-database
    volumes:
      - ./service-database:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"